# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt/settings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(437, 367)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.connection_status = QtWidgets.QLabel(Settings)
        self.connection_status.setText("")
        self.connection_status.setObjectName("connection_status")
        self.horizontalLayout_6.addWidget(self.connection_status)
        self.check_connection = QtWidgets.QPushButton(Settings)
        self.check_connection.setObjectName("check_connection")
        self.horizontalLayout_6.addWidget(self.check_connection)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sign_in_label = QtWidgets.QLabel(Settings)
        self.sign_in_label.setObjectName("sign_in_label")
        self.horizontalLayout.addWidget(self.sign_in_label)
        self.sign_in = QtWidgets.QPushButton(Settings)
        self.sign_in.setObjectName("sign_in")
        self.horizontalLayout.addWidget(self.sign_in)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.file_list_label = QtWidgets.QLabel(Settings)
        self.file_list_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.file_list_label.setObjectName("file_list_label")
        self.verticalLayout.addWidget(self.file_list_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_folder = QtWidgets.QLineEdit(Settings)
        self.file_folder.setEnabled(False)
        self.file_folder.setReadOnly(True)
        self.file_folder.setObjectName("file_folder")
        self.horizontalLayout_2.addWidget(self.file_folder)
        self.select_file_folder = QtWidgets.QPushButton(Settings)
        self.select_file_folder.setObjectName("select_file_folder")
        self.horizontalLayout_2.addWidget(self.select_file_folder)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.output_folder_label = QtWidgets.QLabel(Settings)
        self.output_folder_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.output_folder_label.setObjectName("output_folder_label")
        self.verticalLayout.addWidget(self.output_folder_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.output_folder = QtWidgets.QLineEdit(Settings)
        self.output_folder.setEnabled(False)
        self.output_folder.setText("")
        self.output_folder.setObjectName("output_folder")
        self.horizontalLayout_3.addWidget(self.output_folder)
        self.select_output_folder = QtWidgets.QPushButton(Settings)
        self.select_output_folder.setObjectName("select_output_folder")
        self.horizontalLayout_3.addWidget(self.select_output_folder)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.round_label = QtWidgets.QLabel(Settings)
        self.round_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.round_label.setObjectName("round_label")
        self.horizontalLayout_5.addWidget(self.round_label)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.round_select = QtWidgets.QComboBox(Settings)
        self.round_select.setObjectName("round_select")
        self.verticalLayout.addWidget(self.round_select)
        self.line = QtWidgets.QFrame(Settings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.check_connection.setText(_translate("Settings", "Checking connection..."))
        self.sign_in_label.setText(_translate("Settings", "You are not signed in"))
        self.sign_in.setText(_translate("Settings", "Sign in"))
        self.file_list_label.setText(_translate("Settings", "Folder where the files are stored"))
        self.select_file_folder.setText(_translate("Settings", "Select folder..."))
        self.output_folder_label.setText(_translate("Settings", "Folder where the app will save output"))
        self.select_output_folder.setText(_translate("Settings", "Select folder..."))
        self.round_label.setText(_translate("Settings", "Round"))

