# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_forms/uploader.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(368, 604)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sign_in_section = QtWidgets.QHBoxLayout()
        self.sign_in_section.setObjectName("sign_in_section")
        self.sign_in_label = QtWidgets.QLabel(Form)
        self.sign_in_label.setObjectName("sign_in_label")
        self.sign_in_section.addWidget(self.sign_in_label)
        self.sign_in = QtWidgets.QPushButton(Form)
        self.sign_in.setObjectName("sign_in")
        self.sign_in_section.addWidget(self.sign_in)
        self.verticalLayout.addLayout(self.sign_in_section)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.file_types_label = QtWidgets.QLabel(Form)
        self.file_types_label.setObjectName("file_types_label")
        self.horizontalLayout_9.addWidget(self.file_types_label)
        self.file_types = QtWidgets.QLineEdit(Form)
        self.file_types.setObjectName("file_types")
        self.horizontalLayout_9.addWidget(self.file_types)
        self.videos_radio = QtWidgets.QRadioButton(Form)
        self.videos_radio.setObjectName("videos_radio")
        self.horizontalLayout_9.addWidget(self.videos_radio)
        self.pdfs_radio = QtWidgets.QRadioButton(Form)
        self.pdfs_radio.setObjectName("pdfs_radio")
        self.horizontalLayout_9.addWidget(self.pdfs_radio)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filter_label = QtWidgets.QLabel(Form)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout_4.addWidget(self.filter_label)
        self.filter_box = QtWidgets.QLineEdit(Form)
        self.filter_box.setObjectName("filter_box")
        self.horizontalLayout_4.addWidget(self.filter_box)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.select_folder_section = QtWidgets.QHBoxLayout()
        self.select_folder_section.setObjectName("select_folder_section")
        self.videos_label = QtWidgets.QLabel(Form)
        self.videos_label.setObjectName("videos_label")
        self.select_folder_section.addWidget(self.videos_label)
        self.select_folder = QtWidgets.QPushButton(Form)
        self.select_folder.setObjectName("select_folder")
        self.select_folder_section.addWidget(self.select_folder)
        self.refresh_list = QtWidgets.QPushButton(Form)
        self.refresh_list.setObjectName("refresh_list")
        self.select_folder_section.addWidget(self.refresh_list)
        self.verticalLayout.addLayout(self.select_folder_section)
        self.file_list = QtWidgets.QListWidget(Form)
        self.file_list.setEnabled(True)
        self.file_list.setObjectName("file_list")
        self.verticalLayout.addWidget(self.file_list)
        self.description_label = QtWidgets.QLabel(Form)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.description = QtWidgets.QPlainTextEdit(Form)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.upload = QtWidgets.QPushButton(Form)
        self.upload.setObjectName("upload")
        self.verticalLayout.addWidget(self.upload)
        self.instruction_label = QtWidgets.QLabel(Form)
        self.instruction_label.setWordWrap(True)
        self.instruction_label.setObjectName("instruction_label")
        self.verticalLayout.addWidget(self.instruction_label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Pairwise Comparisons folder structure uploader"))
        self.sign_in_label.setText(_translate("Form", "You are not signed in"))
        self.sign_in.setText(_translate("Form", "Sign in"))
        self.file_types_label.setText(_translate("Form", "File types"))
        self.videos_radio.setText(_translate("Form", "Videos"))
        self.pdfs_radio.setText(_translate("Form", "PDFs"))
        self.filter_label.setText(_translate("Form", "Filter"))
        self.videos_label.setText(_translate("Form", "Files"))
        self.select_folder.setText(_translate("Form", "Select folder"))
        self.refresh_list.setText(_translate("Form", "Refresh list"))
        self.description_label.setText(_translate("Form", "Description"))
        self.upload.setText(_translate("Form", "Upload"))
        self.instruction_label.setText(_translate("Form", "This application uploads the list of videos contained in the folder you select. You can then associate this video list with a round using the online administrator screen at http://education-metrics.appspot.com/pwva. It does not upload the actual videos, only a list of their names and locations within the selected folder."))

