runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /pwv
  static_dir: pwv/static
- url: /pwva.*
  script: pwv.pwv_main.app
- url: /pairwise.*
  script: main.app